# site settings
title: Jessica Giehl
subtitle: WD6 Portfolio Site
email: sumdian@gmail.com
description: Welcome to my portfolio site.
baseurl: "/wd6portfoliosite" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Orlando
state: FL
zip_code:
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: https://github.com/JessGiehl
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
